### ISSUE TITLE
关于ref定义的value

### ISSUE THREAD

**Issue by yangliguo7** [biubiubiu01/vue3-bigData#2]
你在echart封装的组件 
比如 let x =ref(null)
为什么有的用的是 x.value 有的却用的是x呢

**Comment by biubiubiu01** [comment]
js里面.value才能拿到对应的值，只有在template里面才不需要.vaule，直接用x就能拿到值；不知道你所说的是哪个文件。

**Comment by biubiubiu01** [comment]
js里面.value才能拿到对应的值，只有在template里面才不需要.vaule，直接用x就能拿到值；不知道你所说的是哪个文件。
