### ISSUE TITLE
点击年限时间轴时，地图随机乱换了

### ISSUE THREAD

**Issue by HaKLMTT** [biubiubiu01/vue3-bigData#3]
群主，点击下面的时间轴后，地图导航随机的变了，有时候变了市，有时候又莫名调到县了。这是bug吧？

**Comment by biubiubiu01** [comment]
> 群主，点击下面的时间轴后，地图导航随机的变了，有时候变了市，有时候又莫名调到县了。这是bug吧？

这个问题是点击那个时间会触发地图的click事件，点击左右是没问题的，感谢提醒，我再改改。

**Comment by HaKLMTT** [comment]
群主威武，对对，是和地图联动了。辛苦群主。

**Comment by biubiubiu01** [comment]
> 群主威武，对对，是和地图联动了。辛苦群主。

话说为啥叫我群主？

**Comment by HaKLMTT** [comment]
> > 群主威武，对对，是和地图联动了。辛苦群主。
> 
> 话说为啥叫我群主？

哈哈，因为不知道怎么叫好，(#^.^#)

**Comment by HTSmiler** [comment]
为什么下载的安装包损坏了呢？

**Comment by biubiubiu01** [comment]
1
